export var listing={
    city:[
        `city`,`village`,`elector`,`circleCapital`,`capital`,`militaryCapital`,`electorCapital`,`fortified`,
    ],team:[
        `lillebonne`,`montjoie`,`raron`,`chalon`,`queyras`,`leuggern`,`lyon`,`besancon`,`geneva`,`orange`,
        `fenis`,`valais`,`montfaucon`,`gruyeres`,`mirabel`,`laufenburg`,`league of cities`,`genevois`,`forez`,`albon`,
        `zahringen`,`sabran`,`arduinici`,`poitiers`,`rouergue`,`grandson`,`savoy`,`andechs`,`barcelona`,`ecclesiastical`,
        `ecclesiastical2`,`ecclesiastical3`,`arles`,`free company`,`player`,
    ],unit:[
        `0`,`1`,`2`,`3`,`4`,`display`,
    ]
}
export var types={
    city:[],
    team:[],
    cityType:[
        {name:`Base`,term:[0,-1],value:1},//0
        {name:`Village`,term:[1,-1],value:0.5},
        {name:`Electorate`,term:[0,2],value:3},
        {name:`Circle Capital`,term:[3,-1],value:2},
        {name:`Administrative Capital`,term:[4,-1],value:4},
        {name:`Military Capital`,term:[5,-1],value:2},
        {name:`Symbolic Electorate`,term:[4,6],value:5},
    ],map:[
        {
            name:[`Kingdom of Arles`,`Base`],
            term:[`main`,`text`,`full`],
            region:[
                {name:`Transjurania`},
                {name:`Cisjurania`},
                {name:`Provence`},
            ],district:[
                {name:`Léman`,region:``,term:`genevois`},
                {name:`Franche-Comté`,region:`Transjurania`,term:`andechs`},
                {name:`Helvetie`,region:`Transjurania`,term:`zahringen`},
                {name:`Romandie`,region:`Transjurania`,term:`grandson`},
                {name:`Bresse`,region:`Cisjurania`,term:`arduinici`},
                {name:`Alpes`,region:`Cisjurania`,term:`savoy`},
                {name:`Dauphiné`,region:`Cisjurania`,term:`albon`},
                {name:`Drôme`,region:`Provence`,term:`rouergue`},
                {name:`Cottia`,region:`Provence`,term:`sabran`},
                {name:`Provence`,region:`Provence`,term:`barcelona`},
            ],city:[
                [
                    [
                        {name:`Geneva`,type:4,loc:[1821,2199],rule:`Geneva`,district:`Léman`},
                    ],[
                        {name:`Gray`,type:2,loc:[1396,1266],rule:`Andechs`,district:`Franche-Comté`},
                        {name:`Besançon`,type:2,loc:[1657,1375],rule:`Besançon`,district:`Franche-Comté`},
                        {name:`Bern`,type:2,loc:[2465,1514],rule:`League of Cities`,district:`Helvetie`},
                        {name:`Dole`,type:2,loc:[1345,1574],rule:`Andechs`,district:`Franche-Comté`},
                        {name:`Pontarlier`,type:2,loc:[1864,1595],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                        {name:`Thun`,type:2,loc:[2576,1658],rule:`Zähringen`,district:`Helvetie`},
                    ],[
                        {name:`Lyon`,type:2,loc:[1137,2616],rule:`Lyon`,district:`Bresse`},
                        {name:`Vienne`,type:2,loc:[1163,2822],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                        {name:`Grenoble`,type:2,loc:[1667,3002],rule:`Elder Albon`,district:`Dauphiné`},
                        {name:`Albon`,type:2,loc:[1216,3072],rule:`Elder Albon`,district:`Dauphiné`},
                    ],[
                        {name:`Arles`,type:6,loc:[1192,4316],rule:`Archbishop of Arles`,district:`Provence`},
                        {name:`Aix`,type:2,loc:[1667,4376],rule:`Archbishop of Arles`,district:`Provence`},
                        {name:`Marseille`,type:2,loc:[1647,4566],rule:`Barcelona`,district:`Provence`},
                    ],[
                        {name:`Neuchâtel`,type:3,loc:[2172,1515],rule:`Fenis`,district:`Romandie`},
                        {name:`Lausanne`,type:3,loc:[2047,1913],rule:`Archbishop of Besançon`,district:`Romandie`},
                        {name:`Bourg`,type:3,loc:[1295,2243],rule:`Bâgé`,district:`Bresse`},
                        {name:`Chambéry`,type:3,loc:[1751,2719],rule:`Elder Savoy`,district:`Alpes`},
                        {name:`Nyons`,type:3,loc:[1397,3732],rule:`Rouergue`,district:`Drôme`},
                        {name:`Forcalquier`,type:3,loc:[1826,4019],rule:`Sabran`,district:`Cottia`},
                    ],[
                        {name:`Basel`,type:5,loc:[2466,1021],rule:`League of Cities`,district:`Helvetie`},
                        {name:`Lure`,type:5,loc:[1856,1023],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                        {name:`Sion`,type:5,loc:[2476,2093],rule:`Valais`,district:`Helvetie`},
                        {name:`Feurs`,type:5,loc:[805,2726],rule:`Junior Albon`,district:`Dauphiné`},
                        {name:`Viviers`,type:5,loc:[1133,3643],rule:`Archbishop of Arles`,district:`Drôme`},
                        {name:`Nice`,type:5,loc:[2689,4115],rule:`Elder Savoy`,district:`Cottia`},
                    ],
                    //guaranteed cities (small mode)
                ],[
                    [
                        {name:`Arles`,type:6,loc:[1192,4316],rule:`Archbishop of Arles`,district:`Provence`},
                    ],[
                        {name:`Geneva`,type:4,loc:[1821,2199],rule:`Geneva`,district:`Léman`},
                    ],[
                        {name:`Besançon`,type:2,loc:[1657,1375],rule:`Besançon`,district:`Franche-Comté`},
                        {name:`Pontarlier`,type:2,loc:[1864,1595],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    ],[
                        {name:`Lyon`,type:2,loc:[1137,2616],rule:`Lyon`,district:`Bresse`},
                        {name:`Vienne`,type:2,loc:[1163,2822],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    ],[
                        {name:`Aix`,type:2,loc:[1667,4376],rule:`Archbishop of Arles`,district:`Provence`},
                        {name:`Marseille`,type:2,loc:[1647,4566],rule:`Barcelona`,district:`Provence`},
                    ],[
                        {name:`Gray`,type:2,loc:[1396,1266],rule:`Andechs`,district:`Franche-Comté`},
                        {name:`Dole`,type:2,loc:[1345,1574],rule:`Andechs`,district:`Franche-Comté`},
                    ],[
                        {name:`Grenoble`,type:2,loc:[1667,3002],rule:`Elder Albon`,district:`Dauphiné`},
                        {name:`Albon`,type:2,loc:[1216,3072],rule:`Elder Albon`,district:`Dauphiné`},
                    ],[
                        {name:`Bern`,type:2,loc:[2465,1514],rule:`League of Cities`,district:`Helvetie`},
                        {name:`Thun`,type:2,loc:[2576,1658],rule:`Zähringen`,district:`Helvetie`},
                    ],[
                        {name:`Neuchâtel`,type:3,loc:[2172,1515],rule:`Fenis`,district:`Romandie`},
                        {name:`Lausanne`,type:3,loc:[2047,1913],rule:`Archbishop of Besançon`,district:`Romandie`},
                    ],[
                        {name:`Bourg`,type:3,loc:[1310,2243],rule:`Bâgé`,district:`Bresse`},
                        {name:`Chambéry`,type:3,loc:[1751,2719],rule:`Elder Savoy`,district:`Alpes`},
                    ],[
                        {name:`Nyons`,type:3,loc:[1397,3732],rule:`Rouergue`,district:`Drôme`},
                        {name:`Forcalquier`,type:3,loc:[1826,4019],rule:`Sabran`,district:`Cottia`},
                    ],[
                        {name:`Basel`,type:5,loc:[2466,1021],rule:`League of Cities`,district:`Helvetie`},
                        {name:`Lure`,type:5,loc:[1856,1023],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                        {name:`Sion`,type:5,loc:[2476,2093],rule:`Valais`,district:`Helvetie`},
                        {name:`Feurs`,type:5,loc:[805,2726],rule:`Junior Albon`,district:`Dauphiné`},
                        {name:`Viviers`,type:5,loc:[1133,3643],rule:`Archbishop of Arles`,district:`Drôme`},
                        {name:`Nice`,type:5,loc:[2689,4115],rule:`Elder Savoy`,district:`Cottia`},
                    ],
                    //guaranteed cities
                ],[
                    {name:`Laufenburg`,type:0,loc:[2720,997],rule:`Laufenburg`,district:`Helvetie`},

                    {name:`Vesoul`,type:0,loc:[1655,1081],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Montbéliard`,type:0,loc:[2040,1126],rule:`Montfaucon`,district:`Franche-Comté`},
                    {name:`Porrentruy`,type:0,loc:[2204,1172],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Baume-les-Dames`,type:0,loc:[1820,1279],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Solothurn`,type:0,loc:[2470,1294],rule:`League of Cities`,district:`Helvetie`},
                    {name:`Bienne`,type:0,loc:[2315,1378],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Ornans`,type:0,loc:[1743,1463],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Salins`,type:0,loc:[1630,1616],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Meiringen`,type:0,loc:[2865,1640],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Seurre`,type:0,loc:[1187,1641],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Fribourg`,type:0,loc:[2304,1652],rule:`League of Cities`,district:`Helvetie`},
                    {name:`Yverdon`,type:0,loc:[2035,1709],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Gruyères`,type:0,loc:[2288,1841],rule:`Gruyères`,district:`Romandie`},
                    {name:`Foncine`,type:0,loc:[1747,1844],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Lons`,type:0,loc:[1458,1862],rule:`Andechs`,district:`Franche-Comté`},

                    {name:`Visp`,type:0,loc:[2749,2013],rule:`Valais`,district:`Helvetie`},
                    {name:`Nyon`,type:0,loc:[1840,2042],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Aigle`,type:0,loc:[2253,2062],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Thonon`,type:0,loc:[1961,2065],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`St. Claude`,type:0,loc:[1624,2092],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Martigny`,type:0,loc:[2331,2219],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Bonneville`,type:0,loc:[1970,2290],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Varey`,type:0,loc:[1447,2386],rule:`Bâgé`,district:`Bresse`},
                    {name:`Chamonix`,type:0,loc:[2234,2392],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Villefranche`,type:0,loc:[1029,2442],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Annecy`,type:0,loc:[1788,2464],rule:`Thoire`,district:`Léman`},
                    {name:`Roanne`,type:0,loc:[694,2485],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Valbonne`,type:0,loc:[1267,2529],rule:`Bâgé`,district:`Bresse`},
                    {name:`Ugine`,type:0,loc:[2013,2552],rule:`Thoire`,district:`Léman`},
                    {name:`Belley`,type:0,loc:[1588,2609],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Moûtiers`,type:0,loc:[2071,2753],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`La Tour-du-Pin`,type:0,loc:[1484,2761],rule:`Bâgé`,district:`Bresse`},
                    {name:`St. Étienne`,type:0,loc:[915,2925],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`St. Jean`,type:0,loc:[2001,2936],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Beaurepaire`,type:0,loc:[1266,2956],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Vinay`,type:0,loc:[1483,2998],rule:`Elder Albon`,district:`Dauphiné`},

                    {name:`Annonay`,type:0,loc:[1070,3061],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Briançon`,type:0,loc:[2196,3214],rule:`Escartons`,district:`Alpes`},
                    {name:`La Mure`,type:0,loc:[1762,3235],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Valence`,type:0,loc:[1211,3271],rule:`Poitiers`,district:`Drôme`},
                    {name:`Die`,type:0,loc:[1502,3384],rule:`Poitiers`,district:`Drôme`},
                    {name:`St. Bonet`,type:0,loc:[1912,3391],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Embrun`,type:0,loc:[2156,3436],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Privas`,type:0,loc:[1062,3447],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Luc`,type:0,loc:[1569,3500],rule:`Poitiers`,district:`Drôme`},
                    {name:`Gap`,type:0,loc:[1926,3517],rule:`Sabran`,district:`Cottia`},
                    {name:`Aubenas`,type:0,loc:[951,3559],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Montélimar`,type:0,loc:[1162,3573],rule:`Poitiers`,district:`Drôme`},
                    {name:`Barcelonette`,type:0,loc:[2277,3638],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`St. Paul-Trois-Châteaux`,type:0,loc:[1211,3761],rule:`Rouergue`,district:`Drôme`},
                    {name:`Montauban`,type:0,loc:[1635,3781],rule:`Rouergue`,district:`Drôme`},
                    {name:`Sisteron`,type:0,loc:[1885,3812],rule:`Sabran`,district:`Cottia`},
                    {name:`Beuil`,type:0,loc:[2479,3823],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Digne`,type:0,loc:[2060,3891],rule:`Barcelona`,district:`Provence`},
                    {name:`Orange`,type:0,loc:[1249,3923],rule:`Orange`,district:`Drôme`},
                    {name:`Glandèves`,type:0,loc:[2376,3969],rule:`Barcelona`,district:`Provence`},
                    {name:`Carpentras`,type:0,loc:[1394,3997],rule:`Rouergue`,district:`Drôme`},

                    {name:`Castellane`,type:0,loc:[2242,4056],rule:`Barcelona`,district:`Provence`},
                    {name:`Vence`,type:0,loc:[2589,4068],rule:`Barcelona`,district:`Provence`},
                    {name:`Avignon`,type:0,loc:[1283,4085],rule:`Rouergue`,district:`Drôme`},
                    {name:`Riez`,type:0,loc:[2011,4096],rule:`Barcelona`,district:`Provence`},
                    {name:`Apt`,type:0,loc:[1596,4102],rule:`Sabran`,district:`Cottia`},
                    {name:`Pertuis`,type:0,loc:[1689,4242],rule:`Sabran`,district:`Cottia`},
                    {name:`Cannes`,type:0,loc:[2548,4250],rule:`Barcelona`,district:`Provence`},
                    {name:`Draguignan`,type:0,loc:[2244,4306],rule:`Barcelona`,district:`Provence`},
                    {name:`Salon`,type:0,loc:[1464,4311],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Fréjus`,type:0,loc:[2409,4360],rule:`Barcelona`,district:`Provence`},
                    {name:`Istres`,type:0,loc:[1404,4424],rule:`Barcelona`,district:`Provence`},
                    {name:`Brignoles`,type:0,loc:[2039,4435],rule:`Barcelona`,district:`Provence`},
                    {name:`Fraxinetum`,type:0,loc:[2261,4476],rule:`Barcelona`,district:`Provence`},
                    {name:`Martigues`,type:0,loc:[1453,4508],rule:`Barcelona`,district:`Provence`},
                    {name:`Toulon`,type:0,loc:[1983,4641],rule:`Barcelona`,district:`Provence`},
                    {name:`Hyères`,type:0,loc:[2110,4675],rule:`Barcelona`,district:`Provence`},
                    //chance cities
                ],[
                    {name:`Vauvillers`,type:1,loc:[1651,858],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Fougerolles`,type:1,loc:[1831,858],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Faucogney`,type:1,loc:[1905,889],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Luxeuil`,type:1,loc:[1783,915],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Conflans`,type:1,loc:[1698,919],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Jussey`,type:1,loc:[1549,929],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Leuggern`,type:1,loc:[2792,953],rule:`Leuggern`,district:`Helvetie`},
                    
                    {name:`Châlonvillars`,type:1,loc:[2008,1005],rule:`Montfaucon`,district:`Franche-Comté`},
                    {name:`Rheinfelden`,type:1,loc:[2584,1012],rule:`League of Cities`,district:`Helvetie`},
                    {name:`Saulx`,type:1,loc:[1727,1021],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Combeaufontaine`,type:1,loc:[1502,1023],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Villingen`,type:1,loc:[2804,1023],rule:`Laufenburg`,district:`Helvetie`},
                    {name:`Frick`,type:1,loc:[2677,1025],rule:`Laufenburg`,district:`Helvetie`},
                    {name:`Port`,type:1,loc:[1602,1036],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Montjustin`,type:1,loc:[1823,1070],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Arlesheim`,type:1,loc:[2479,1071],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Liestal`,type:1,loc:[2552,1071],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Kasteln`,type:1,loc:[2768,1074],rule:`Laufenburg`,district:`Helvetie`},
                    {name:`Héricourt`,type:1,loc:[2015,1079],rule:`Montfaucon`,district:`Franche-Comté`},
                    {name:`Granges`,type:1,loc:[1891,1100],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Laufen`,type:1,loc:[2430,1142],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Champlitte`,type:1,loc:[1342,1149],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Waldenburg`,type:1,loc:[2572,1151],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Fresne`,type:1,loc:[1551,1153],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Bure`,type:1,loc:[2159,1159],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Olten`,type:1,loc:[2646,1163],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Dampierre`,type:1,loc:[1410,1165],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Beinwil`,type:1,loc:[2493,1169],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Rougemont`,type:1,loc:[1789,1175],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Delémont`,type:1,loc:[2354,1186],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`L'Isle`,type:1,loc:[1922,1205],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Blamont`,type:1,loc:[2080,1214],rule:`Montfaucon`,district:`Franche-Comté`},
                    {name:`St. Ursanne`,type:1,loc:[2250,1216],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Härkingen`,type:1,loc:[2614,1232],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Rioz`,type:1,loc:[1645,1236],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Montjoie`,type:1,loc:[2115,1241],rule:`Montjoie`,district:`Franche-Comté`},
                    {name:`Moutier`,type:1,loc:[2376,1257],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Wiedlisbach`,type:1,loc:[2532,1263],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Bellelay`,type:1,loc:[2259,1271],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Gy`,type:1,loc:[1527,1274],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Langental`,type:1,loc:[2608,1286],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Belvoir`,type:1,loc:[1971,1290],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Saignelégier`,type:1,loc:[2176,1304],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Herzogenbuchsee`,type:1,loc:[2568,1311],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Châtillon-le-Duc`,type:1,loc:[1643,1315],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Cusance`,type:1,loc:[1875,1318],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Grenchen`,type:1,loc:[2400,1328],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Thise`,type:1,loc:[1703,1340],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Marnay`,type:1,loc:[1493,1355],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Pelousey`,type:1,loc:[1596,1361],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Buchegg`,type:1,loc:[2461,1361],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Hutwil`,type:1,loc:[2651,1362],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Russey`,type:1,loc:[2042,1364],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Perrigny`,type:1,loc:[1316,1379],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`St. Imier`,type:1,loc:[2185,1391],rule:`Montfaucon`,district:`Romandie`},
                    {name:`Diesse`,type:1,loc:[2260,1397],rule:`Montfaucon`,district:`Romandie`},
                    {name:`Nidau`,type:1,loc:[2325,1401],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Mamirolle`,type:1,loc:[1757,1410],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Sumiswald`,type:1,loc:[2609,1416],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Pesmes`,type:1,loc:[1370,1419],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Burgdorf`,type:1,loc:[2536,1420],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Orchamps`,type:1,loc:[1944,1422],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Valdahon`,type:1,loc:[1832,1424],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`St. Vit`,type:1,loc:[1535,1443],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`La Neuveville`,type:1,loc:[2251,1443],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Aarberg`,type:1,loc:[2341,1450],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Ranflüh`,type:1,loc:[2606,1469],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Zollikofen`,type:1,loc:[2446,1471],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Cerlier`,type:1,loc:[2260,1472],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Lavanage`,type:1,loc:[1446,1477],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Morteau`,type:1,loc:[1990,1482],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Valangin`,type:1,loc:[2165,1487],rule:`Fenis`,district:`Romandie`},
                    {name:`Quigney`,type:1,loc:[1599,1497],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Auxonne`,type:1,loc:[1296,1499],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Vullafans`,type:1,loc:[1790,1500],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Escholzmatt`,type:1,loc:[2720,1510],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Lièvremont`,type:1,loc:[1919,1519],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Signau`,type:1,loc:[2607,1520],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Rochefort`,type:1,loc:[2106,1524],rule:`Fenis`,district:`Romandie`},
                    {name:`Authume`,type:1,loc:[1365,1533],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Amancey`,type:1,loc:[1707,1541],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Morat`,type:1,loc:[2284,1551],rule:[`Zähringen`,`Junior Savoy`],district:`Romandie`},
                    {name:`Konolfingen`,type:1,loc:[2551,1553],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Belp`,type:1,loc:[2488,1555],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Cudrefin`,type:1,loc:[2213,1556],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Laupen`,type:1,loc:[2349,1562],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Arc`,type:1,loc:[1521,1576],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Travers`,type:1,loc:[1986,1583],rule:`Fenis`,district:`Romandie`},
                    {name:`La Vieille`,type:1,loc:[1439,1585],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Pagny`,type:1,loc:[1220,1586],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Gorgier`,type:1,loc:[2093,1587],rule:`Fenis`,district:`Romandie`},
                    {name:`Schangnau`,type:1,loc:[2685,1591],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Vivy`,type:1,loc:[2311,1593],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Avenches`,type:1,loc:[2240,1596],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Levier`,type:1,loc:[1723,1606],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Rüeggisberg`,type:1,loc:[2454,1618],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Grasbourg`,type:1,loc:[2410,1629],rule:[`Zähringen`,`Junior Savoy`],district:`Romandie`},
                    {name:`Brienz`,type:1,loc:[2788,1629],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Steffisburg`,type:1,loc:[2557,1631],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Tavaux`,type:1,loc:[1297,1635],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Estavayer`,type:1,loc:[2141,1636],rule:`Fenis`,district:`Romandie`},
                    {name:`Gadmen`,type:1,loc:[2962,1636],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Payerne`,type:1,loc:[2191,1649],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Parcey`,type:1,loc:[1333,1653],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Vaudrey`,type:1,loc:[1432,1653],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Ringgenberg`,type:1,loc:[2734,1660],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Montagny`,type:1,loc:[2226,1663],rule:`Fenis`,district:`Romandie`},
                    {name:`Innertkirchen`,type:1,loc:[2911,1664],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Grandson`,type:1,loc:[2034,1667],rule:`Laufenburg`,district:`Helvetie`,district:`Romandie`},
                    {name:`Frasne`,type:1,loc:[1778,1672],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Arbois`,type:1,loc:[1545,1679],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Arconciel`,type:1,loc:[2306,1691],rule:`Fenis`,district:`Romandie`},
                    {name:`Andelot`,type:1,loc:[1634,1694],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Interlaken`,type:1,loc:[2693,1696],rule:`Archbishop of Besançon`,district:`Helvetie`},
                    {name:`Spiez`,type:1,loc:[2595,1716],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Les Clées`,type:1,loc:[1958,1717],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Grindelwald`,type:1,loc:[2799,1724],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Jougne`,type:1,loc:[1885,1726],rule:`Archbishop of Besançon`,district:`Franche-Comté`},
                    {name:`Handegg`,type:1,loc:[2943,1727],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Poligny`,type:1,loc:[1522,1732],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Weissenburg`,type:1,loc:[2505,1732],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Villarzel`,type:1,loc:[2204,1737],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Planfayon`,type:1,loc:[2402,1746],rule:`Fenis`,district:`Romandie`},
                    {name:`Sellières`,type:1,loc:[1430,1748],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Nozeroy`,type:1,loc:[1721,1750],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Mülenen`,type:1,loc:[2614,1750],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Orbe`,type:1,loc:[1980,1752],rule:`Montfaucon`,district:`Romandie`},
                    {name:`Moudon`,type:1,loc:[2136,1775],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Romont`,type:1,loc:[2232,1776],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Champagnole`,type:1,loc:[1651,1783],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Mouthe`,type:1,loc:[1808,1784],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Lauterbrunnen`,type:1,loc:[2741,1786],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Romainmôtier`,type:1,loc:[1926,1788],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Corbières`,type:1,loc:[2309,1789],rule:`Gruyères`,district:`Romandie`},
                    {name:`Frutigen`,type:1,loc:[2587,1790],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Ulrichen`,type:1,loc:[2965,1797],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Arlay`,type:1,loc:[1423,1802],rule:`Chalon`,district:`Franche-Comté`},
                    {name:`Échallens`,type:1,loc:[2042,1806],rule:`Montfaucon`,district:`Romandie`},
                    {name:`Mirabel-Hauteroche`,type:1,loc:[1544,1834],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Blankenburg`,type:1,loc:[2463,1842],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Goms`,type:1,loc:[2934,1851],rule:`Valais`,district:`Helvetie`},
                    {name:`Adelboden`,type:1,loc:[2558,1853],rule:`Zähringen`,district:`Helvetie`},
                    {name:`Oron`,type:1,loc:[2152,1865],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Doucier`,type:1,loc:[1582,1867],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Bellwald`,type:1,loc:[2889,1892],rule:`Raron`,district:`Romandie`},
                    {name:`Saanen`,type:1,loc:[2379,1897],rule:`Gruyères`,district:`Romandie`},
                    {name:`Albeuve`,type:1,loc:[2272,1898],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Bière`,type:1,loc:[1878,1901],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`La Lenk`,type:1,loc:[2495,1901],rule:`Zähringen`,district:`Helvetie`},
                    {name:`La Chaux`,type:1,loc:[1657,1902],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Wilen`,type:1,loc:[2702,1915],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Belalp`,type:1,loc:[2793,1916],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Morges`,type:1,loc:[1975,1919],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Cully`,type:1,loc:[2105,1927],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Sonnette`,type:1,loc:[1404,1934],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Grengiols`,type:1,loc:[2864,1937],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Clairvaux`,type:1,loc:[1576,1938],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Aubonne`,type:1,loc:[1918,1941],rule:`Gruyères`,district:`Romandie`},
                    {name:`Morbier`,type:1,loc:[1734,1947],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Vevey`,type:1,loc:[2178,1952],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Gsteig`,type:1,loc:[2403,1966],rule:`Gruyères`,district:`Romandie`},
                    {name:`Rolle`,type:1,loc:[1887,1981],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Chillon`,type:1,loc:[2230,1981],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Brig`,type:1,loc:[2809,1982],rule:`Valais`,district:`Helvetie`},
                    {name:`Cressia`,type:1,loc:[1414,1997],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Orgelet`,type:1,loc:[1514,1999],rule:`Andechs`,district:`Franche-Comté`},
                    
                    {name:`Raron`,type:1,loc:[2707,2001],rule:[`Raron`,`Valais`],district:`Romandie`},
                    {name:`Aigremont`,type:1,loc:[2311,2007],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Nanchez`,type:1,loc:[1605,2008],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Leuk`,type:1,loc:[2616,2008],rule:`Valais`,district:`Helvetie`},
                    {name:`Évian`,type:1,loc:[2043,2014],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`St. Gingolph`,type:1,loc:[2165,2015],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Ayent`,type:1,loc:[2496,2018],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Bonmont`,type:1,loc:[1789,2029],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Sierre`,type:1,loc:[2542,2045],rule:`Valais`,district:`Helvetie`},
                    {name:`Yvoire`,type:1,loc:[1895,2061],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Abondance`,type:1,loc:[2091,2064],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`St. Trivier`,type:1,loc:[1188,2068],rule:`Bâgé`,district:`Bresse`},
                    {name:`Arinthod`,type:1,loc:[1493,2082],rule:`Andechs`,district:`Franche-Comté`},
                    {name:`Simplon`,type:1,loc:[2851,2082],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Monthey`,type:1,loc:[2238,2097],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Gex`,type:1,loc:[1737,2101],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Coligny`,type:1,loc:[1311,2102],rule:`Bâgé`,district:`Bresse`},
                    {name:`Bex`,type:1,loc:[2286,2114],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Anniviers`,type:1,loc:[2595,2116],rule:`Raron`,district:`Romandie`},
                    {name:`Conthey`,type:1,loc:[2431,2118],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Foissat`,type:1,loc:[1246,2124],rule:`Bâgé`,district:`Bresse`},
                    {name:`Bons`,type:1,loc:[1936,2135],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`St. Maurice`,type:1,loc:[2281,2139],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Hérémence`,type:1,loc:[2505,2144],rule:`Archbishop of Besançon`,district:`Romandie`},
                    {name:`Ferney`,type:1,loc:[1782,2149],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Meinier`,type:1,loc:[1859,2154],rule:`Archbishop of Vienne`,district:`Léman`},
                    {name:`Miribel-Mégevette`,type:1,loc:[2009,2163],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Saillon`,type:1,loc:[2381,2164],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Bâgé`,type:1,loc:[1119,2169],rule:`Bâgé`,district:`Bresse`},
                    {name:`Oyonnax`,type:1,loc:[1550,2169],rule:`Bâgé`,district:`Bresse`},
                    {name:`Morzine`,type:1,loc:[2123,2175],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Satigny`,type:1,loc:[1750,2188],rule:`Lillebonne`,district:`Léman`},
                    {name:`Bogève`,type:1,loc:[1967,2200],rule:`Archbishop of Vienne`,district:`Léman`},
                    {name:`Meillonnas`,type:1,loc:[1382,2201],rule:`Bâgé`,district:`Bresse`},
                    {name:`Giron`,type:1,loc:[1587,2216],rule:`Bâgé`,district:`Bresse`},
                    {name:`Onnion`,type:1,loc:[2033,2217],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Izernore`,type:1,loc:[1475,2218],rule:`Bâgé`,district:`Bresse`},
                    {name:`Jasseron`,type:1,loc:[1365,2235],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Contamine`,type:1,loc:[1911,2245],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Taninges`,type:1,loc:[2073,2248],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`St. Julien`,type:1,loc:[1785,2251],rule:`Thoire`,district:`Léman`},
                    {name:`Vonnas`,type:1,loc:[1186,2252],rule:`Bâgé`,district:`Bresse`},
                    {name:`Collonges`,type:1,loc:[1678,2254],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Nantua`,type:1,loc:[1513,2277],rule:`Bâgé`,district:`Bresse`},
                    {name:`Valleiry`,type:1,loc:[1721,2282],rule:`Thoire`,district:`Léman`},
                    {name:`Orsières`,type:1,loc:[2370,2285],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Sixt`,type:1,loc:[2165,2286],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Bellegarde`,type:1,loc:[1630,2288],rule:`Bâgé`,district:`Bresse`},
                    {name:`Thoissey`,type:1,loc:[1080,2289],rule:`Thoire`,district:`Bresse`},
                    {name:`Cluses`,type:1,loc:[2070,2294],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Valloreine`,type:1,loc:[2276,2296],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`La Roche`,type:1,loc:[1911,2316],rule:`Thoire`,district:`Léman`},
                    {name:`Varax`,type:1,loc:[1268,2318],rule:`Thoire`,district:`Bresse`},
                    {name:`Poncin`,type:1,loc:[1399,2326],rule:`Bâgé`,district:`Bresse`},
                    {name:`Relevant`,type:1,loc:[1187,2329],rule:`Thoire`,district:`Bresse`},
                    {name:`Magland`,type:1,loc:[2107,2343],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Cruseilles`,type:1,loc:[1799,2344],rule:`Thoire`,district:`Léman`},
                    {name:`Belleville`,type:1,loc:[1049,2350],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Franclens`,type:1,loc:[1635,2357],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Valromey`,type:1,loc:[1551,2360],rule:`Bâgé`,district:`Bresse`},
                    {name:`Charousse`,type:1,loc:[2141,2383],rule:`Thoire`,district:`Léman`},
                    {name:`La Pacaudière`,type:1,loc:[583,2399],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Chalamont`,type:1,loc:[1290,2400],rule:`Thoire`,district:`Bresse`},
                    {name:`La Balme`,type:1,loc:[1743,2405],rule:`Thoire`,district:`Léman`},
                    {name:`Villaz`,type:1,loc:[1872,2408],rule:`Thoire`,district:`Léman`},
                    {name:`Villars`,type:1,loc:[1220,2409],rule:`Thoire`,district:`Bresse`},
                    {name:`Fareins`,type:1,loc:[1075,2412],rule:`Thoire`,district:`Bresse`},
                    {name:`Seyssel`,type:1,loc:[1650,2416],rule:`Thoire`,district:`Léman`},
                    {name:`Amberieu`,type:1,loc:[1368,2428],rule:`Archbishop of Arles`,district:`Alpes`},
                    {name:`La Clusaz`,type:1,loc:[2007,2430],rule:`Thoire`,district:`Léman`},
                    {name:`Megève`,type:1,loc:[2121,2443],rule:`Junior Savoy`,district:`Romandie`},
                    {name:`Thônes`,type:1,loc:[1927,2458],rule:`Thoire`,district:`Léman`},
                    {name:`St. André`,type:1,loc:[1181,2459],rule:`Bâgé`,district:`Bresse`},
                    {name:`Létra`,type:1,loc:[932,2465],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Lagnieu`,type:1,loc:[1378,2470],rule:`Thoire`,district:`Bresse`},
                    {name:`Meximieux`,type:1,loc:[1301,2473],rule:`Bâgé`,district:`Bresse`},
                    {name:`Trévoux`,type:1,loc:[1088,2477],rule:`Thoire`,district:`Bresse`},
                    {name:`Artemare`,type:1,loc:[1559,2484],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Flumet`,type:1,loc:[2061,2491],rule:`Thoire`,district:`Léman`},
                    {name:`Culoz`,type:1,loc:[1636,2493],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Rumilly`,type:1,loc:[1711,2495],rule:`Thoire`,district:`Léman`},
                    {name:`Ouches`,type:1,loc:[637,2508],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Anse`,type:1,loc:[1050,2510],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Miribel`,type:1,loc:[1200,2514],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Amplepuis`,type:1,loc:[799,2519],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Villebois`,type:1,loc:[1432,2537],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Doussard`,type:1,loc:[1872,2539],rule:`Thoire`,district:`Léman`},
                    {name:`Tarare`,type:1,loc:[899,2545],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Hauteluce`,type:1,loc:[2098,2549],rule:`Thoire`,district:`Léman`},
                    {name:`Faverges`,type:1,loc:[1946,2554],rule:`Thoire`,district:`Léman`},
                    {name:`Limonest`,type:1,loc:[1077,2557],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`L'Arbresle`,type:1,loc:[986,2575],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Hautecombe`,type:1,loc:[1681,2575],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Villeurbanne`,type:1,loc:[1179,2576],rule:`Bâgé`,district:`Bresse`},
                    {name:`Loyette`,type:1,loc:[1331,2580],rule:`Bâgé`,district:`Bresse`},
                    {name:`Vézelin`,type:1,loc:[747,2595],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Violay`,type:1,loc:[904,2601],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Meyzieu`,type:1,loc:[1219,2604],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Albertville`,type:1,loc:[1981,2605],rule:`Thoire`,district:`Léman`},
                    {name:`St. Just`,type:1,loc:[590,2614],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Lhuis`,type:1,loc:[1513,2615],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Lescheraines`,type:1,loc:[1850,2617],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Aix-les-Bains`,type:1,loc:[1733,2622],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Crémieu`,type:1,loc:[1354,2625],rule:`Bâgé`,district:`Bresse`},
                    {name:`Craponne`,type:1,loc:[1055,2627],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Souternon`,type:1,loc:[684,2631],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Bourg-St. Maurice`,type:1,loc:[2229,2632],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Lutrin`,type:1,loc:[1679,2633],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Civens`,type:1,loc:[856,2657],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Genas`,type:1,loc:[1239,2661],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Le Bourget`,type:1,loc:[1712,2663],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`La Plagne`,type:1,loc:[2165,2680],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Vénissieux`,type:1,loc:[1146,2681],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Colombier`,type:1,loc:[1323,2682],rule:`Bâgé`,district:`Bresse`},
                    {name:`Morestel`,type:1,loc:[1484,2683],rule:`Bâgé`,district:`Bresse`},
                    {name:`Duerne`,type:1,loc:[975,2690],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Brignais`,type:1,loc:[1098,2692],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`St. Pierre`,type:1,loc:[1904,2703],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Urfe`,type:1,loc:[607,2707],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Tignes`,type:1,loc:[2313,2711],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Novalaise`,type:1,loc:[1666,2712],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Bourgoin-Jallieu`,type:1,loc:[1397,2720],rule:`Bâgé`,district:`Bresse`},
                    {name:`Aiguebelle`,type:1,loc:[1980,2720],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Boën`,type:1,loc:[711,2723],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Aoste`,type:1,loc:[1570,2729],rule:`Bâgé`,district:`Bresse`},
                    {name:`Marennes`,type:1,loc:[1184,2736],rule:`Bâgé`,district:`Bresse`},
                    {name:`Mornant`,type:1,loc:[1057,2737],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`St. Symphorien`,type:1,loc:[931,2746],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Villefontaine`,type:1,loc:[1322,2747],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Givors`,type:1,loc:[1092,2760],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Domessin`,type:1,loc:[1632,2760],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Montmélian`,type:1,loc:[1819,2765],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Bonneval`,type:1,loc:[2383,2785],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Sauvain`,type:1,loc:[656,2795],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Épierre`,type:1,loc:[1958,2795],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Chazelles`,type:1,loc:[958,2802],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Courchevel`,type:1,loc:[2188,2804],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Arvillard`,type:1,loc:[1878,2808],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Montbrison`,type:1,loc:[732,2810],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Montrond`,type:1,loc:[829,2810],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Biol`,type:1,loc:[1452,2822],rule:`Bâgé`,district:`Bresse`},
                    {name:`Miribel-les-Échelles`,type:1,loc:[1644,2822],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Méribel`,type:1,loc:[2081,2823],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Savas`,type:1,loc:[1260,2832],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Rive`,type:1,loc:[1020,2834],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Voiron`,type:1,loc:[1595,2845],rule:`Bâgé`,district:`Bresse`},
                    {name:`Bessans`,type:1,loc:[2354,2852],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Condrieu`,type:1,loc:[1109,2869],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`St. Rambert`,type:1,loc:[832,2877],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`La Chambre`,type:1,loc:[1985,2879],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`St. Chamond`,type:1,loc:[968,2881],rule:`Archbishop of Vienne`,district:`Bresse`},
                    {name:`Pontcharra`,type:1,loc:[1786,2881],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Clermont`,type:1,loc:[1531,2883],rule:`Bâgé`,district:`Bresse`},
                    {name:`Carthause`,type:1,loc:[1708,2884],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`La Côte`,type:1,loc:[1383,2892],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Lanslebourg`,type:1,loc:[2281,2894],rule:`Archbishop of Vienne`,district:`Alpes`},
                    {name:`Izeaux`,type:1,loc:[1480,2895],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Primarette`,type:1,loc:[1252,2915],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Miribel-Périgneux`,type:1,loc:[797,2923],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Voreppe`,type:1,loc:[1608,2926],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Chanas`,type:1,loc:[1126,2938],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Modane`,type:1,loc:[2201,2961],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Firminy`,type:1,loc:[878,2962],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Roybon`,type:1,loc:[1387,2962],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Meylan`,type:1,loc:[1702,2969],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`St. Michel`,type:1,loc:[2092,2982],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Vaujany`,type:1,loc:[1870,2984],rule:`Elder Albon`,district:`Dauphiné`},
                    
                    {name:`Andance`,type:1,loc:[1123,3005],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Galaure`,type:1,loc:[1223,3005],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Argental`,type:1,loc:[1008,3009],rule:`Archbishop of Vienne`,district:`Dauphiné`},
                    {name:`Valloire`,type:1,loc:[2055,3030],rule:`Elder Savoy`,district:`Alpes`},
                    {name:`Miribel-Valherbasse`,type:1,loc:[1306,3057],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`St. Vallier`,type:1,loc:[1153,3059],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`St. Marcellin`,type:1,loc:[1437,3059],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Lans`,type:1,loc:[1585,3062],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Bourg d'Oisans`,type:1,loc:[1890,3076],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Vizelle`,type:1,loc:[1716,3085],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Ozon`,type:1,loc:[1153,3105],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Villard`,type:1,loc:[1562,3114],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Lauzet`,type:1,loc:[2089,3127],rule:`Escartons`,district:`Alpes`},
                    {name:`La Grave`,type:1,loc:[1987,3128],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Vif`,type:1,loc:[1649,3130],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Pont`,type:1,loc:[1469,3131],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Tournon`,type:1,loc:[1160,3154],rule:`Poitiers`,district:`Drôme`},
                    {name:`St. Félicien`,type:1,loc:[1032,3158],rule:`Junior Albon`,district:`Dauphiné`},
                    {name:`Névache`,type:1,loc:[2210,3168],rule:`Escartons`,district:`Alpes`},
                    {name:`Romans`,type:1,loc:[1296,3170],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Miribel-Lanchâtre`,type:1,loc:[1630,3192],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Oriol`,type:1,loc:[1419,3195],rule:`Poitiers`,district:`Drôme`},
                    {name:`La Chapelle`,type:1,loc:[1515,3210],rule:`Poitiers`,district:`Drôme`},
                    {name:`Glun`,type:1,loc:[1181,3217],rule:`Poitiers`,district:`Drôme`},
                    {name:`Alixan`,type:1,loc:[1286,3227],rule:`Poitiers`,district:`Drôme`},
                    {name:`Monestier`,type:1,loc:[1664,3237],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Vallouise`,type:1,loc:[2111,3247],rule:`Escartons`,district:`Alpes`},
                    {name:`Cervières`,type:1,loc:[2250,3249],rule:`Escartons`,district:`Alpes`},
                    {name:`Désaignes`,type:1,loc:[1000,3262],rule:`Poitiers`,district:`Drôme`},
                    {name:`Alboussière`,type:1,loc:[1114,3266],rule:`Poitiers`,district:`Drôme`},
                    {name:`Vassieux`,type:1,loc:[1497,3275],rule:`Poitiers`,district:`Drôme`},
                    {name:`Ristolans`,type:1,loc:[2365,3286],rule:`Escartons`,district:`Alpes`},
                    {name:`Chabeuil`,type:1,loc:[1286,3293],rule:`Poitiers`,district:`Drôme`},
                    {name:`L'Argentière`,type:1,loc:[2167,3301],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Soyons`,type:1,loc:[1187,3303],rule:`Poitiers`,district:`Drôme`},
                    {name:`Corps`,type:1,loc:[1855,3307],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Omblèze`,type:1,loc:[1415,3314],rule:`Poitiers`,district:`Drôme`},
                    {name:`Clelles`,type:1,loc:[1654,3317],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Mens`,type:1,loc:[1738,3318],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Queyras`,type:1,loc:[2273,3322],rule:`Escartons`,district:`Alpes`},
                    {name:`Le Cheylard`,type:1,loc:[944,3325],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Chalançon`,type:1,loc:[1060,3339],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Lesdiguierès`,type:1,loc:[1891,3343],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Romeyer`,type:1,loc:[1539,3362],rule:`Poitiers`,district:`Drôme`},
                    {name:`Champoléon`,type:1,loc:[2012,3367],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`St. Martial`,type:1,loc:[852,3368],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`La Voulte`,type:1,loc:[1181,3373],rule:`Poitiers`,district:`Drôme`},
                    {name:`Guillestre`,type:1,loc:[2209,3394],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Mézilhac`,type:1,loc:[937,3405],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Mirabel-et-Blacons`,type:1,loc:[1366,3406],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Livron`,type:1,loc:[1185,3415],rule:`Poitiers`,district:`Drôme`},
                    {name:`Dévoluy`,type:1,loc:[1859,3420],rule:`Sabran`,district:`Cottia`},
                    {name:`Grâne`,type:1,loc:[1251,3421],rule:`Poitiers`,district:`Drôme`},
                    {name:`Orciéres`,type:1,loc:[2059,3422],rule:`Elder Albon`,district:`Dauphiné`},
                    {name:`Vars`,type:1,loc:[2295,3432],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Châtillon`,type:1,loc:[1579,3435],rule:`Poitiers`,district:`Drôme`},
                    {name:`Crest`,type:1,loc:[1315,3436],rule:`Poitiers`,district:`Drôme`},
                    {name:`Lus`,type:1,loc:[1720,3444],rule:`Sabran`,district:`Cottia`},
                    {name:`Coucouron`,type:1,loc:[718,3446],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Saillans`,type:1,loc:[1396,3447],rule:`Poitiers`,district:`Drôme`},
                    {name:`Ancelle`,type:1,loc:[1979,3460],rule:`Sabran`,district:`Cottia`},
                    {name:`Baix`,type:1,loc:[1151,3467],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Boule`,type:1,loc:[1637,3467],rule:`Poitiers`,district:`Drôme`},
                    {name:`Saou`,type:1,loc:[1318,3498],rule:`Poitiers`,district:`Drôme`},
                    {name:`Marsanne`,type:1,loc:[1242,3507],rule:`Poitiers`,district:`Drôme`},
                    {name:`Les Orres`,type:1,loc:[2197,3511],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Savines`,type:1,loc:[2099,3513],rule:`Sabran`,district:`Cottia`},
                    {name:`Chorges`,type:1,loc:[2034,3515],rule:`Sabran`,district:`Cottia`},
                    {name:`Cruas`,type:1,loc:[1155,3523],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Mayres`,type:1,loc:[834,3527],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Manteyer`,type:1,loc:[1879,3530],rule:`Sabran`,district:`Cottia`},
                    {name:`Beaurières`,type:1,loc:[1646,3536],rule:`Poitiers`,district:`Drôme`},
                    {name:`St. Nazaire`,type:1,loc:[1460,3540],rule:`Poitiers`,district:`Drôme`},
                    {name:`Veynes`,type:1,loc:[1799,3543],rule:`Sabran`,district:`Cottia`},
                    {name:`Mirabel`,type:1,loc:[1017,3550],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Sceautres`,type:1,loc:[1090,3553],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Tallard`,type:1,loc:[1914,3588],rule:`Sabran`,district:`Cottia`},
                    {name:`Jausiers`,type:1,loc:[2358,3591],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Vesc`,type:1,loc:[1390,3592],rule:`Poitiers`,district:`Drôme`},
                    {name:`Le Teil`,type:1,loc:[1137,3600],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Dieulefit`,type:1,loc:[1332,3602],rule:`Poitiers`,district:`Drôme`},
                    {name:`La Bégude`,type:1,loc:[1249,3603],rule:`Rouergue`,district:`Drôme`},
                    {name:`La Motte`,type:1,loc:[1535,3603],rule:`Rouergue`,district:`Drôme`},
                    {name:`Le Lauzet`,type:1,loc:[2109,3612],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`St. Andéol`,type:1,loc:[1051,3626],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Chaudebonne`,type:1,loc:[1450,3628],rule:`Rouergue`,district:`Drôme`},
                    {name:`Thinas`,type:1,loc:[804,3629],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Serres`,type:1,loc:[1750,3632],rule:`Sabran`,district:`Cottia`},
                    {name:`Largentière`,type:1,loc:[920,3634],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Barcillonnette`,type:1,loc:[1854,3645],rule:`Sabran`,district:`Cottia`},
                    {name:`Montclar`,type:1,loc:[2031,3650],rule:`Sabran`,district:`Cottia`},
                    {name:`Donzère`,type:1,loc:[1162,3659],rule:`Rouergue`,district:`Drôme`},
                    {name:`Rémuzat`,type:1,loc:[1518,3672],rule:`Rouergue`,district:`Drôme`},
                    {name:`Rosans`,type:1,loc:[1610,3676],rule:`Rouergue`,district:`Drôme`},
                    {name:`Uvernet`,type:1,loc:[2253,3687],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Seyne`,type:1,loc:[2108,3689],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Gras`,type:1,loc:[1058,3699],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Grignan`,type:1,loc:[1259,3700],rule:`Rouergue`,district:`Drôme`},
                    {name:`Venterol`,type:1,loc:[1387,3709],rule:`Rouergue`,district:`Drôme`},
                    {name:`St. Étienne-de-Tinée`,type:1,loc:[2460,3712],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Orpierre`,type:1,loc:[1740,3718],rule:`Sabran`,district:`Cottia`},
                    {name:`Valréas`,type:1,loc:[1328,3723],rule:`Rouergue`,district:`Drôme`},
                    {name:`Joyeuse`,type:1,loc:[899,3726],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Vallon`,type:1,loc:[989,3727],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Clamensane`,type:1,loc:[1950,3728],rule:`Sabran`,district:`Cottia`},
                    {name:`Estenc`,type:1,loc:[2355,3730],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Pierrelatte`,type:1,loc:[1150,3747],rule:`Rouergue`,district:`Drôme`},
                    {name:`Barles`,type:1,loc:[2066,3760],rule:`Barcelona`,district:`Provence`},
                    {name:`Isola`,type:1,loc:[2543,3761],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Mison`,type:1,loc:[1819,3775],rule:`Sabran`,district:`Cottia`},
                    {name:`Tulete`,type:1,loc:[1295,3780],rule:`Rouergue`,district:`Drôme`},
                    {name:`Mirabel-aux-Baronnies`,type:1,loc:[1381,3780],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Colmars`,type:1,loc:[2287,3788],rule:`Barcelona`,district:`Provence`},
                    {name:`Lapalad`,type:1,loc:[1140,3794],rule:`Archbishop of Arles`,district:`Drôme`},
                    {name:`Buis`,type:1,loc:[1491,3809],rule:`Rouergue`,district:`Drôme`},
                    {name:`Guillaumes`,type:1,loc:[2412,3810],rule:`Barcelona`,district:`Provence`},
                    {name:`Suze`,type:1,loc:[1263,3813],rule:`Rouergue`,district:`Drôme`},
                    {name:`Le Brusquet`,type:1,loc:[2115,3817],rule:`Barcelona`,district:`Provence`},
                    {name:`Bollène`,type:1,loc:[1190,3823],rule:`Rouergue`,district:`Drôme`},
                    {name:`St. Martin-Vésubie`,type:1,loc:[2659,3828],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Mévouillon`,type:1,loc:[1624,3830],rule:`Rouergue`,district:`Drôme`},
                    {name:`Vaison`,type:1,loc:[1396,3832],rule:`Rouergue`,district:`Drôme`},
                    {name:`St. Cécile`,type:1,loc:[1290,3847],rule:`Rouergue`,district:`Drôme`},
                    {name:`Séderon`,type:1,loc:[1669,3848],rule:`Rouergue`,district:`Drôme`},
                    {name:`Noyers`,type:1,loc:[1830,3848],rule:`Sabran`,district:`Cottia`},
                    {name:`Thorame`,type:1,loc:[2259,3857],rule:`Barcelona`,district:`Provence`},
                    {name:`Mondragon`,type:1,loc:[1177,3877],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Roquebillière`,type:1,loc:[2696,3880],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Brantes`,type:1,loc:[1559,3882],rule:`Rouergue`,district:`Drôme`},
                    {name:`Gigondas`,type:1,loc:[1354,3890],rule:`Orange`,district:`Drôme`},
                    {name:`Malaucène`,type:1,loc:[1436,3894],rule:`Rouergue`,district:`Drôme`},
                    {name:`Redortiers`,type:1,loc:[1686,3895],rule:`Sabran`,district:`Cottia`},
                    {name:`Château-Arnoux`,type:1,loc:[1936,3899],rule:`Sabran`,district:`Cottia`},
                    {name:`Pierlas`,type:1,loc:[2566,3908],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Cruis`,type:1,loc:[1852,3932],rule:`Sabran`,district:`Cottia`},
                    {name:`Malijai`,type:1,loc:[1956,3934],rule:`Barcelona`,district:`Provence`},
                    {name:`Sault`,type:1,loc:[1583,3939],rule:`Rouergue`,district:`Drôme`},
                    {name:`Puget-Théniers`,type:1,loc:[2464,3942],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Allons`,type:1,loc:[2281,3944],rule:`Barcelona`,district:`Provence`},
                    {name:`Jonquières`,type:1,loc:[1313,3949],rule:`Orange`,district:`Drôme`},
                    {name:`Mézel`,type:1,loc:[2052,3961],rule:`Barcelona`,district:`Provence`},
                    {name:`Banon`,type:1,loc:[1731,3964],rule:`Sabran`,district:`Cottia`},
                    {name:`Mormoiron`,type:1,loc:[1467,3983],rule:`Rouergue`,district:`Drôme`},
                    {name:`St. Christol`,type:1,loc:[1627,3986],rule:`Sabran`,district:`Cottia`},
                    {name:`Lurs`,type:1,loc:[1895,3992],rule:`Archbishop of Arles`,district:`Cottia`},
                    {name:`Roquesteron`,type:1,loc:[2529,3996],rule:`Elder Savoy`,district:`Cottia`},
                    
                    {name:`Senez`,type:1,loc:[2182,4000],rule:`Barcelona`,district:`Provence`},
                    {name:`Levens`,type:1,loc:[2654,4000],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`L'Escarène`,type:1,loc:[2728,4003],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Simiane-la-Rotonde`,type:1,loc:[1695,4020],rule:`Sabran`,district:`Cottia`},
                    {name:`Sorgues`,type:1,loc:[1290,4022],rule:`Rouergue`,district:`Drôme`},
                    {name:`Venasque`,type:1,loc:[1449,4025],rule:`Rouergue`,district:`Drôme`},
                    {name:`Oraison`,type:1,loc:[1899,4040],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Auban`,type:1,loc:[2348,4047],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Saturnin`,type:1,loc:[1586,4061],rule:`Sabran`,district:`Cottia`},
                    {name:`Drap`,type:1,loc:[2719,4062],rule:`Elder Savoy`,district:`Cottia`},
                    {name:`Thor`,type:1,loc:[1372,4081],rule:`Rouergue`,district:`Drôme`},
                    {name:`Reillane`,type:1,loc:[1762,4092],rule:`Sabran`,district:`Cottia`},
                    {name:`Gordes`,type:1,loc:[1488,4103],rule:`Rouergue`,district:`Drôme`},
                    {name:`Caussols`,type:1,loc:[2472,4105],rule:`Barcelona`,district:`Provence`},
                    {name:`Aiguines`,type:1,loc:[2104,4118],rule:`Barcelona`,district:`Provence`},
                    {name:`Manosque`,type:1,loc:[1840,4119],rule:`Sabran`,district:`Cottia`},
                    {name:`Céreste`,type:1,loc:[1697,4122],rule:`Sabran`,district:`Cottia`},
                    {name:`La Colette`,type:1,loc:[2407,4126],rule:`Barcelona`,district:`Provence`},
                    {name:`Châteaurenard`,type:1,loc:[1286,4136],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Laurent`,type:1,loc:[2628,4137],rule:`Barcelona`,district:`Provence`},
                    {name:`Cavaillon`,type:1,loc:[1400,4150],rule:`Rouergue`,district:`Drôme`},
                    {name:`Ménerbes`,type:1,loc:[1531,4153],rule:`Rouergue`,district:`Drôme`},
                    {name:`Comps`,type:1,loc:[2261,4161],rule:`Barcelona`,district:`Provence`},
                    {name:`Grasse`,type:1,loc:[2502,4177],rule:`Barcelona`,district:`Provence`},
                    {name:`Sénas`,type:1,loc:[1418,4201],rule:`Barcelona`,district:`Provence`},
                    {name:`La Tour-d'Aigues`,type:1,loc:[1717,4202],rule:`Sabran`,district:`Cottia`},
                    {name:`Vinon`,type:1,loc:[1871,4204],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Remy`,type:1,loc:[1286,4207],rule:`Barcelona`,district:`Provence`},
                    {name:`Tarascon`,type:1,loc:[1168,4208],rule:`Barcelona`,district:`Provence`},
                    {name:`Cadenet`,type:1,loc:[1584,4212],rule:`Sabran`,district:`Cottia`},
                    {name:`Fayence`,type:1,loc:[2370,4222],rule:`Barcelona`,district:`Provence`},
                    {name:`Régusse`,type:1,loc:[2047,4223],rule:`Barcelona`,district:`Provence`},
                    {name:`Antibes`,type:1,loc:[2621,4225],rule:`Barcelona`,district:`Provence`},
                    {name:`Mirabel-Andaon`,type:1,loc:[1775,4228],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Ampus`,type:1,loc:[2197,4228],rule:`Barcelona`,district:`Provence`},
                    {name:`Mallemort`,type:1,loc:[1471,4231],rule:`Barcelona`,district:`Provence`},
                    {name:`Bargemon`,type:1,loc:[2292,4231],rule:`Barcelona`,district:`Provence`},
                    {name:`Baux`,type:1,loc:[1267,4250],rule:`Barcelona`,district:`Provence`},
                    {name:`Eyguières`,type:1,loc:[1391,4260],rule:`Barcelona`,district:`Provence`},
                    {name:`Lérins`,type:1,loc:[2581,4267],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Fontvieille`,type:1,loc:[1201,4268],rule:`Barcelona`,district:`Provence`},
                    {name:`Lambesc`,type:1,loc:[1525,4279],rule:`Barcelona`,district:`Provence`},
                    {name:`Peyrolles`,type:1,loc:[1743,4282],rule:`Barcelona`,district:`Provence`},
                    {name:`Rognes`,type:1,loc:[1592,4283],rule:`Barcelona`,district:`Provence`},
                    {name:`Fourques`,type:1,loc:[1166,4286],rule:`Rouergue`,district:`Drôme`},
                    {name:`Les Adrets`,type:1,loc:[2452,4287],rule:`Barcelona`,district:`Provence`},
                    {name:`Salernes`,type:1,loc:[2117,4289],rule:`Barcelona`,district:`Provence`},
                    {name:`Rians`,type:1,loc:[1846,4305],rule:`Barcelona`,district:`Provence`},
                    {name:`Barjols`,type:1,loc:[1988,4311],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Martin`,type:1,loc:[1299,4320],rule:`Barcelona`,district:`Provence`},
                    {name:`Lorques`,type:1,loc:[2182,4344],rule:`Barcelona`,district:`Provence`},
                    {name:`Éguilles`,type:1,loc:[1601,4350],rule:`Barcelona`,district:`Provence`},
                    {name:`Cornillon`,type:1,loc:[1454,4354],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Le Muy`,type:1,loc:[2329,4354],rule:`Barcelona`,district:`Provence`},
                    {name:`Vauvenargues`,type:1,loc:[1758,4359],rule:`Barcelona`,district:`Provence`},
                    {name:`Miramas`,type:1,loc:[1408,4362],rule:`Barcelona`,district:`Provence`},
                    {name:`Albaron`,type:1,loc:[1109,4366],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Velaux`,type:1,loc:[1546,4379],rule:`Barcelona`,district:`Provence`},
                    {name:`Le Luc`,type:1,loc:[2115,4396],rule:`Barcelona`,district:`Provence`},
                    {name:`Agon`,type:1,loc:[1168,4397],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Vidauban`,type:1,loc:[2248,4397],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Maximin`,type:1,loc:[1899,4399],rule:`Barcelona`,district:`Provence`},
                    {name:`Rousset`,type:1,loc:[1785,4415],rule:`Barcelona`,district:`Provence`},
                    {name:`Trets`,type:1,loc:[1827,4434],rule:`Barcelona`,district:`Provence`},
                    {name:`Berre`,type:1,loc:[1510,4437],rule:`Barcelona`,district:`Provence`},
                    {name:`Gardanne`,type:1,loc:[1699,4437],rule:`Barcelona`,district:`Provence`},
                    {name:`Le Sambuc`,type:1,loc:[1247,4439],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Fos`,type:1,loc:[1340,4449],rule:`Barcelona`,district:`Provence`},
                    {name:`Tourves`,type:1,loc:[1957,4459],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Mitre`,type:1,loc:[1431,4465],rule:`Barcelona`,district:`Provence`},
                    {name:`Les Mayons`,type:1,loc:[2179,4467],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Maxime`,type:1,loc:[2365,4471],rule:`Barcelona`,district:`Provence`},
                    {name:`Rougiers`,type:1,loc:[1908,4473],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Marignane`,type:1,loc:[1522,4476],rule:`Barcelona`,district:`Provence`},
                    {name:`Septèmes`,type:1,loc:[1635,4483],rule:`Barcelona`,district:`Provence`},
                    {name:`Auriol`,type:1,loc:[1805,4493],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Maries`,type:1,loc:[1086,4494],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`St. Tropez`,type:1,loc:[2380,4506],rule:`Barcelona`,district:`Provence`},
                    {name:`Port-St. Louis`,type:1,loc:[1282,4508],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Garéoult`,type:1,loc:[2036,4512],rule:`Barcelona`,district:`Provence`},
                    {name:`Roquevaire`,type:1,loc:[1770,4516],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`Carnoules`,type:1,loc:[2123,4522],rule:`Barcelona`,district:`Provence`},
                    {name:`St. Baume`,type:1,loc:[1875,4526],rule:`Barcelona`,district:`Provence`},
                    {name:`Mirabelle`,type:1,loc:[1693,4533],rule:`Mirabel`,district:`Dauphiné`},
                    {name:`Cogolin`,type:1,loc:[2309,4533],rule:`Barcelona`,district:`Provence`},
                    {name:`Carry`,type:1,loc:[1514,4539],rule:`Barcelona`,district:`Provence`},
                    {name:`Aubagne`,type:1,loc:[1764,4550],rule:`Barcelona`,district:`Provence`},
                    {name:`Méounes`,type:1,loc:[1992,4550],rule:`Barcelona`,district:`Provence`},
                    {name:`Solliès`,type:1,loc:[2041,4597],rule:`Barcelona`,district:`Provence`},
                    {name:`Cavalaire`,type:1,loc:[2310,4600],rule:`Barcelona`,district:`Provence`},
                    {name:`Cassis`,type:1,loc:[1743,4602],rule:`Barcelona`,district:`Provence`},
                    {name:`Bormes`,type:1,loc:[2183,4610],rule:`Barcelona`,district:`Provence`},
                    {name:`Le Beausset`,type:1,loc:[1909,4611],rule:`Archbishop of Arles`,district:`Provence`},
                    {name:`La Ciotat`,type:1,loc:[1782,4623],rule:`Barcelona`,district:`Provence`},
                    {name:`Cabasson`,type:1,loc:[2223,4657],rule:`Barcelona`,district:`Provence`},
                    {name:`Bandol`,type:1,loc:[1869,4659],rule:`Barcelona`,district:`Provence`},
                    {name:`Sanary`,type:1,loc:[1911,4677],rule:`Barcelona`,district:`Provence`},
                ],
            ],team:[
                {name:`Lillebonne`,term:`lillebonne`,quality:1},
                {name:`Montjoie`,term:`montjoie`,quality:1},
                {name:`Leuggern`,term:`leuggern`,quality:1.1},
                {name:`Raron`,term:`raron`,quality:1},
                {name:`Lyon`,term:`lyon`,quality:0.95},
                {name:`Besançon`,term:`besancon`,quality:0.95},
                {name:`Geneva`,term:`geneva`,quality:0.95},
                {name:`Laufenburg`,term:`laufenburg`,quality:1},
                {name:`Orange`,term:`orange`,quality:1},
                {name:`Fenis`,term:`fenis`,quality:1},
                {name:`Escartons`,term:`queyras`,quality:1.1},
                {name:`Valais`,term:`valais`,quality:1},
                {name:`Montfaucon`,term:`montfaucon`,quality:1},
                {name:`Gruyères`,term:`gruyeres`,quality:1},
                {name:`Chalon`,term:`chalon`,quality:1},
                {name:`Mirabel`,term:`mirabel`,quality:1},
                {name:`League of Cities`,term:`league of cities`,quality:0.95},
                {name:`Thoire`,term:`genevois`,quality:1},
                {name:`Junior Albon`,term:`forez`,quality:1},
                {name:`Elder Albon`,term:`albon`,quality:1},
                {name:`Zähringen`,term:`zahringen`,quality:1},
                {name:`Sabran`,term:`sabran`,quality:1},
                {name:`Bâgé`,term:`arduinici`,quality:1},
                {name:`Poitiers`,term:`poitiers`,quality:1},
                {name:`Rouergue`,term:`rouergue`,quality:1},
                {name:`Junior Savoy`,term:`grandson`,quality:1},
                {name:`Elder Savoy`,term:`savoy`,quality:1},
                {name:`Andechs`,term:`andechs`,quality:1},
                {name:`Barcelona`,term:`barcelona`,quality:1},
                {name:`Archbishop of Besançon`,term:`ecclesiastical3`,quality:0.9},
                {name:`Archbishop of Vienne`,term:`ecclesiastical`,quality:0.9},
                {name:`Archbishop of Arles`,term:`ecclesiastical2`,quality:0.9},

                {name:`Royal Army`,term:`arles`,quality:1},
                {name:`Free Company`,term:`free company`,quality:1.4},
                {name:`Player`,term:`player`,quality:1.5},
            ],
        },
    ],
}
export var dev={water:false,view:false,district:false}
export var options={strength:1,unitSize:1,scale:1,difficulty:1,allCity:false,size:1}
export var graphics={main:0,load:{map:[],city:[],team:[],unit:[]}}
export var constants={trig:[[],[]],init:false,unitNum:10}
export var inputs={mouse:{base:{x:0,y:0},rel:{x:0,y:0},previous:{base:{x:0,y:0},rel:{x:0,y:0}}}}